# Generated by Django 3.2.7 on 2021-09-30 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_auto_20210930_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('classCode', models.CharField(max_length=200)),
                ('courseTitle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sampleField', models.CharField(max_length=200)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorAppointment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('examplefield', models.CharField(max_length=200)),
                ('active', models.IntegerField()),
                ('home_department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.courseinstructor')),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.instructor')),
            ],
        ),
        migrations.AddField(
            model_name='courseinstructor',
            name='instructor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.instructor'),
        ),
    ]
